config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :conversations do
    resources :messages
  end

  root to: 'main#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable

  acts_as_messageable

  def name
    "User #{id}"
  end

  def mailboxer_email(object)
    nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @conversations = current_user.mailbox.conversations
  end

  def show
    @conversation = current_user.mailbox.conversations.find(params[:id])
  end

  def new
    @recipients = User.all - [current_user]
  end

  def create
    recipient = User.find(params[:user_id])
    receipt   = current_user.send_message(recipient, params[:body], params[:subject])
    redirect_to conversation_path(receipt.conversation)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_conversation

  def create
    receipt = current_user.reply_to_conversation(@conversation, params[:body])
    redirect_to conversation_path(receipt.conversation)
  end

  private

    def set_conversation
      @conversation = current_user.mailbox.conversations.find(params[:conversation_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/conversations/index.html.erb
<h1>All Conversations</h1>

<% @conversations.each do |conversation| %>
  <div>
    <%= link_to conversation.subject, conversation_path(conversation) %>
  </div>
<% end %>

<%= link_to "New Conversation", new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= form_tag conversations_path, method: :post do %>
  <div>
    <%= select_tag :user_id, options_from_collection_for_select(@recipients, :id, :name) %>
  </div>

  <div>
    <%= text_field_tag :subject, nil, placeholder: "Subject" %>
  </div>

  <div>
    <%= text_area_tag :body, nil, placeholder: "Leave a comment" %>
  </div>

  <%= submit_tag %>
<% end %>

app/views/conversations/show.html.erb
<h1><%= @conversation.subject %></h1>

<% @conversation.receipts_for(current_user).each do |receipt| %>
  <div>
    <div><%= receipt.message.sender.name %> commented:</div>
    <p><%= receipt.message.body %></p>
  </div>
<% end %>

<%= form_tag conversation_messages_path(@conversation), method: :post do %>
  <div>
    <%= text_area_tag :body %>
  </div>

  <%= submit_tag %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Messager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>